---
title: "supfig01"
author: "kaehwan"
date: "6/15/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
true <- TRUE
false <- FALSE
```

#### Load libraries

```{r}
source("configuration.R")
library(wesanderson)
pacman::p_load("ggtext")
```

#### Checking assembled genome completeness of four enrichment fractions from assembly-based analytics

```{r}
# Read in data
dat <- read.table("../tables/metagenomics.metaphlan4.pilot.s.gbs.txt", 
                  header=true, row.names=1) %>% 
        mutate(across(where(is.numeric), round, digits=2)) %>% 
        select(Library, Enrichment, GBS_assembly_detected, 
               GBS_assembly_typed, GBS_assembly_genome_length) 

dat %>% 
        mutate(Assembly_genome_length=if_else(GBS_assembly_detected=="No",
                                              0,
                                              GBS_assembly_genome_length),
               Enrichment=factor(Enrichment, levels=c("Pre", "eTHB", "eBHI", "chromID"))) %>% 
        ggplot(aes(x=Enrichment ,y=GBS_assembly_genome_length/2.21e6*100, fill=Enrichment)) +
        geom_bar(stat="identity", position=position_dodge()) +
        scale_fill_manual(values=wes_palette(n=4, name="GrandBudapest1")) +
        theme(axis.text.x=element_text(size=20),
              legend.text=element_markdown(),
              legend.position="none") +
        labs(x="Enrichment fraction", y="Assembled genome completeness (%)")
ggsave('../output_figures/supfig01_b_illumina_pilot_assembly_genome_qc.svg', 
       width =12, height = 8)

```

#### Heatmap summary of spike-in samples in assembly-based analysis workflow

```{r}
meta <- read.table("../metadata/metagenomics_spike_metadata.txt",
                   header=TRUE, sep="\t") %>% 
        rename(sample_id=Sample_ID, spike_level=GBS_spike_level, SI=GBS_isolation, 
               mgD=GBS_assembly_detected, mgT=GBS_assembly_seqTyped) %>% 
        select(sample_id, spike_level, SI, mgD, mgT) %>% 
        mutate(spike_level=recode(spike_level, '1-log'='10^1 - 10^2', 
                                  '2-log'='10^2 - 10^3', '3-log'='10^3 - 10^4', 
                                  '4-log'='10^4 - 10^5'), )

meta %>% 
        pivot_longer(-c('sample_id', 'spike_level'), names_to='workflows', values_to='values') %>% 
        mutate(spike_level=factor(spike_level, levels=c('Non-spike', '10^1 - 10^2', 
                                                        '10^2 - 10^3', '10^3 - 10^4', 
                                                        '10^4 - 10^5')), 
               workflows=factor(workflows, levels=c('SI', 'mgD', 'mgT')),
               values=factor(values, levels=c('Yes', 'No'))) %>% 
        ggplot(aes(x=workflows, y=sample_id, fill=values)) +
        geom_tile(color='black', size=0.35) +
        facet_grid(.~ spike_level) +
        coord_fixed() +
        scale_fill_manual(name='', values=c('brown', 'lightgrey')) +
        labs(x='', y='Samples', title="GBS spike level (cfu)") +
        theme(panel.border=element_blank(),
              axis.ticks=element_blank(),
              plot.title=element_text(size=22),
              axis.text.x=element_text(angle=45, hjust=1, vjust=1),
              strip.text.x=element_markdown(),
              strip.background=element_blank())
ggsave('../output_figures/supfig01_c_illumina_spike_assembly_analysis_summary.svg', 
       width=14, height=8)

```

#### Assembled genome completeness of assembly-based metagenomics analytics workflow

```{r}
meta.assembled <- read.table("../metadata/metagenomics_spike_metadata.txt",
                             header=TRUE, sep="\t") %>% 
        select(Library, GBS_spike_level, GBS_assembly_genome_length) %>% 
        rename(spike_level=GBS_spike_level, genome_length=GBS_assembly_genome_length) %>% 
        mutate(spike_level=recode(spike_level, '1-log'='10^1 - 10^2', 
                                  '2-log'='10^2 - 10^3', '3-log'='10^3 - 10^4', 
                                  '4-log'='10^4 - 10^5'),
               analytics="Assembly")
meta.mapping <- read.table("../metadata/metagenomics_spike_metadata.txt",
                             header=TRUE, sep="\t") %>% 
        select(Library, GBS_spike_level, GBS_map_genome_length) %>% 
        rename(spike_level=GBS_spike_level, genome_length=GBS_map_genome_length) %>% 
        mutate(spike_level=recode(spike_level, '1-log'='10^1 - 10^2', 
                                  '2-log'='10^2 - 10^3', '3-log'='10^3 - 10^4', 
                                  '4-log'='10^4 - 10^5'),
               analytics="Mapping")
df <- rbind(meta.assembled, meta.mapping)

# create plot using ggplot() and geom_boxplot() functions
df %>% filter(spike_level %in% c("10^2 - 10^3", "10^3 - 10^4", "10^4 - 10^5")) %>% 
        mutate(genome_completeness=genome_length/2.21e6*100) %>% 
        ggplot(., aes(analytics, genome_completeness, fill=analytics)) +
        facet_grid(cols=vars(spike_level), scale="free") + 
        geom_boxplot() +
        # geom_point() is used to make points at data values
        geom_point(aes(fill=analytics,group=Library), size=5,
                   shape=21, position=position_jitter(w=0.05, h=2)) +
        # geom_line() joins the paired datapoints
        geom_line(aes(group=Library), linetype=2, size=1.3) +
        labs(x="Analytics workflow", y="Assembled genome<br>completeness (%)") +
        theme(axis.title.y=element_markdown(),
              legend.position="none",
              strip.text=element_markdown(),
              strip.background=element_blank())
ggsave('../output_figures/supfig01_d_illumina_spike_assembly_vs_mapping_analysis.svg', 
       width=14, height=8)

```

#### Session info

```{r}
sessionInfo()
```